### ISSUE TITLE
The <RCircularBuffer.h> library is not available

### ISSUE THREAD

**Issue by pascalstark** [matteobaccan/PassiveCooker#2]
The used library <RCircularBuffer.h> is not available. Tried the CircularBuffer.h library, but that didn't work.

**Comment by matteobaccan** [comment]
Hi

the original source released by Barilla has this problem.
I have tried to fix it in the release I pushed today.

I have also added a .yml for the automatic creation of Arduino binary.

I hope this can help you.

ciao
matteo

**Comment by pascalstark** [comment]
Hi matteo, 
Thank you for your quick reply and providing the library and additional information. I will test it in the next few days.

best regards,
Pascal
