### ISSUE TITLE
Code Problem

### ISSUE THREAD

**Issue by rdfry** [matteobaccan/PassiveCooker#7]
When i run the arduino ide i get RCircular buffer not found

**Comment by rdfry** [comment]
i just realized the library i need is here

**Comment by matteobaccan** [comment]
I have had the same problem and I have fixed the issue in this repository

Tell me if you have problems using it

**Comment by rdfry** [comment]
I was able to install the RCircular Buffer folder and compiled and uploaded to the nano 33 ble. The problem i was having was because on the barilla website they only have the Arduino Sketch and don't include any info on the Rcircular Buffer Folder. Thanks for getting back to me.

    On Saturday, March 4, 2023 at 01:52:32 AM CST, Matteo Baccan ***@***.***> wrote:  
 
 


I have had the same problem and I have fixed the issue in this repository

Tell me if you have problems using it

**Comment by matteobaccan** [comment]
Yes a common problem

I also released the binary version compiled with a guthub actions

Feel free to do a PR if you made changes

**Comment by rdfry** [comment]
Thanks again. I was able to successfully compile it once I had the RCircular Buffer folder and upload to the board.
    On Saturday, March 4, 2023 at 02:20:53 AM CST, Matteo Baccan ***@***.***> wrote:  
 
 


Yes a common problem

I also released the binary version compiled with a guthub actions

Feel free to do a PR if you made changes

**Comment by rdfry** [comment]
hey where do the magnets go ? Barilla has no real instructions on this

    On Saturday, March 4, 2023 at 01:52:32 AM CST, Matteo Baccan ***@***.***> wrote:  
 
 


I have had the same problem and I have fixed the issue in this repository

Tell me if you have problems using it

**Comment by matteobaccan** [comment]
Sorry: I don't known

**Comment by rdfry** [comment]
ok thanks
    On Wednesday, March 8, 2023 at 01:42:18 AM CST, Matteo Baccan ***@***.***> wrote:  
 
 


Sorry: I don't known
